### PR TITLE
Added the stats side by side..

### PR DESCRIPTION
**Pull request by AviralCoder**
To make your README bootiful, I added the stats side by side 😎

### CODE REVIEW

**Comment by AviralCoder** [comment]
Oh.......preview -

**Comment by AviralCoder** [comment]
PREVIEW---
Screenshot 2021-10-04 at 7 52 52 PM

**Comment by AviralCoder** [comment]
BTW........I changed ---  to *** because apparently it was not working...

**Comment by BhavyaCodes** [comment]
Thanks!

**Comment by AviralCoder** [comment]
Your welcome 😃

**Pull request merged**
